spring:
  profiles:
    active: dev
  datasource:
    url:  jdbc:sqlite:account.db
    driver-class-name: org.sqlite.JDBC
  thymeleaf:
    content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    
bmob:
  app-id: 37b79d1b03807693a777002779739d61
  rest-api-key: 3a4e7412d1d8822f077cd78c2449147a
  
  
## Local Enviroment ##########
---  
spring:
  profiles: dev
  thymeleaf:
    cache: true
  
server:
  port: 8080
  host: localhost
  
logging:
  file: log.txt
  level:
    root: INFO
    

## SSL Enviroment ##########
---
spring:
  profiles: prd
  thymeleaf:
    cache: false
  
server:
  port: 443
  host: www.jchen.club
  ssl:
    key-store: classpath:jchen_letsencrypt.jks
    key-store-password: denni0616
    keyStoreType: JKS
    keyAlias: tomcat_letsencrypt
