spring:
  profiles:
    active: dev
  
## Local Enviroment ##########
---  
spring:
  profiles: dev
server:
  port: 8080
  host: localhost

## SSL Enviroment ##########
---
spring:
  profiles: prd
server:
  port: 443
  host: www.jchen.club
  ssl:
    key-store: classpath:jchen_letsencrypt.jks
    key-store-password: denni0616
    keyStoreType: JKS
    keyAlias: tomcat_letsencrypt
